package Forme;

import javax.swing.JOptionPane;

public class GlavnaForma extends javax.swing.JFrame {

    public GlavnaForma() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreirajKozmeticara = new javax.swing.JButton();
        txtBrisanjeKozmeticara = new javax.swing.JButton();
        btnIzmenaKozmeticara = new javax.swing.JButton();
        btnKreiranjeUsluge = new javax.swing.JButton();
        btnPretragaUsluga = new javax.swing.JButton();
        btnObrisiUslugu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnKreiranjeTermina = new javax.swing.JButton();
        btnIzmenaTermina = new javax.swing.JButton();
        btnBrisanjeTermina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacija kozmetickog salona");

        btnKreirajKozmeticara.setText("Kreiraj kozmeticara");
        btnKreirajKozmeticara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajKozmeticaraActionPerformed(evt);
            }
        });

        txtBrisanjeKozmeticara.setText("Brisanje kozmeticara");
        txtBrisanjeKozmeticara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrisanjeKozmeticaraActionPerformed(evt);
            }
        });

        btnIzmenaKozmeticara.setText("Izmena kozmeticara");
        btnIzmenaKozmeticara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaKozmeticaraActionPerformed(evt);
            }
        });

        btnKreiranjeUsluge.setText("Kreiranje usluge");
        btnKreiranjeUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreiranjeUslugeActionPerformed(evt);
            }
        });

        btnPretragaUsluga.setText("Pretraga usluga");
        btnPretragaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaUslugaActionPerformed(evt);
            }
        });

        btnObrisiUslugu.setText("Brisanje usluge");
        btnObrisiUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUsluguActionPerformed(evt);
            }
        });

        jLabel1.setText("Dobrodosli!");

        btnKreiranjeTermina.setText("Kreiranje termina");
        btnKreiranjeTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreiranjeTerminaActionPerformed(evt);
            }
        });

        btnIzmenaTermina.setText("Izmena termina");
        btnIzmenaTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaTerminaActionPerformed(evt);
            }
        });

        btnBrisanjeTermina.setText("Brisanje termina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnKreiranjeTermina)
                        .addGap(112, 112, 112)
                        .addComponent(btnIzmenaTermina))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKreiranjeUsluge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKreirajKozmeticara, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmenaKozmeticara, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPretragaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrisanjeKozmeticara, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBrisanjeTermina)
                                    .addComponent(btnObrisiUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajKozmeticara)
                    .addComponent(btnIzmenaKozmeticara)
                    .addComponent(txtBrisanjeKozmeticara))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiranjeUsluge)
                    .addComponent(btnPretragaUsluga)
                    .addComponent(btnObrisiUslugu))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiranjeTermina)
                    .addComponent(btnIzmenaTermina)
                    .addComponent(btnBrisanjeTermina))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajKozmeticaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajKozmeticaraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novog kozmeticara");
        KreirajKozmeticaraForma kkf = new KreirajKozmeticaraForma();
        this.setVisible(false);
        kkf.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novog kozmeticara");
    }//GEN-LAST:event_btnKreirajKozmeticaraActionPerformed

    private void txtBrisanjeKozmeticaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrisanjeKozmeticaraActionPerformed
        // TODO add your handling code here:
        BrisanjeKozmeticaraForma bkf = new BrisanjeKozmeticaraForma();
        this.setVisible(false);
        bkf.setVisible(true);
    }//GEN-LAST:event_txtBrisanjeKozmeticaraActionPerformed

    private void btnIzmenaKozmeticaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaKozmeticaraActionPerformed
        // TODO add your handling code here:
        IzmenaKozmeticaraForma ikf = new IzmenaKozmeticaraForma();
        this.setVisible(false);
        ikf.setVisible(true);
    }//GEN-LAST:event_btnIzmenaKozmeticaraActionPerformed

    private void btnKreiranjeUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreiranjeUslugeActionPerformed
        // TODO add your handling code here:

        KreiranjeUslugeForma kuf = new KreiranjeUslugeForma();
        this.setVisible(false);
        kuf.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novu uslugu");
    }//GEN-LAST:event_btnKreiranjeUslugeActionPerformed

    private void btnPretragaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaUslugaActionPerformed
        // TODO add your handling code here:
        PretrazivanjeUsluge pu = new PretrazivanjeUsluge();
        this.setVisible(false);
        pu.setVisible(true);
    }//GEN-LAST:event_btnPretragaUslugaActionPerformed

    private void btnObrisiUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUsluguActionPerformed
        // TODO add your handling code here:
        BrisanjeUslugeForma buf = new BrisanjeUslugeForma();
        this.setVisible(false);
        buf.setVisible(true);
    }//GEN-LAST:event_btnObrisiUsluguActionPerformed

    private void btnKreiranjeTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreiranjeTerminaActionPerformed
        // TODO add your handling code here:
        KreiranjeTerminaForma ktf = new KreiranjeTerminaForma();
        this.setVisible(false);
        ktf.setVisible(true);
    }//GEN-LAST:event_btnKreiranjeTerminaActionPerformed

    private void btnIzmenaTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaTerminaActionPerformed
        // TODO add your handling code here:
        IzmenaTerminaForma itf = new IzmenaTerminaForma();
        this.setVisible(false);
        itf.setVisible(true);
    }//GEN-LAST:event_btnIzmenaTerminaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanjeTermina;
    private javax.swing.JButton btnIzmenaKozmeticara;
    private javax.swing.JButton btnIzmenaTermina;
    private javax.swing.JButton btnKreirajKozmeticara;
    private javax.swing.JButton btnKreiranjeTermina;
    private javax.swing.JButton btnKreiranjeUsluge;
    private javax.swing.JButton btnObrisiUslugu;
    private javax.swing.JButton btnPretragaUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtBrisanjeKozmeticara;
    // End of variables declaration//GEN-END:variables

}
