/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Beans.KategorijaUsluga;
import Beans.Usluga;
import ClientRequests.AddNewServiceRequest;
import ClientRequests.RequestTypes;
import ServerReplies.AddNewServiceReply;
import ServerReplies.VratiSveKategorijeUslugaOdgovor;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;

/**
 *
 * @author milic
 */
public class KreiranjeUslugeForma extends javax.swing.JFrame {

    /**
     * Creates new form KreiranjeUslugeForma
     */
    public KreiranjeUslugeForma() {
        initComponents();
        popuniCmbKategorijaUsluge();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNazivUsluge = new javax.swing.JTextField();
        cmbKategorijaUsluga = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbKategorijaUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNazivUsluge)
                            .addComponent(cmbKategorijaUsluga, 0, 235, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtNazivUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(cmbKategorijaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnSacuvaj)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            String naziv = txtNazivUsluge.getText();
            KategorijaUsluga kategorija = (KategorijaUsluga) cmbKategorijaUsluga.getSelectedItem();
            Usluga usluga = new Usluga(0, naziv, kategorija.getKategorijaId());
            
            if(naziv.isEmpty() || cmbKategorijaUsluga.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(this, "Polja ne smeju biti prazna!");
            }
            
            AddNewServiceRequest zahtev = new AddNewServiceRequest(usluga);
            
            KomunikacijaSaServerom.getInstanca().getOos().writeInt(RequestTypes.ADD_NEW_SERVICE_REQUEST);
            KomunikacijaSaServerom.getInstanca().getOos().writeObject(zahtev);
            
            int tipOdgovora = KomunikacijaSaServerom.getInstanca().getOis().readInt();
            AddNewServiceReply odgovor = (AddNewServiceReply) KomunikacijaSaServerom.getInstanca().getOis().readObject();
            if(odgovor.isSuccess()){
                JOptionPane.showMessageDialog(this, "Usluga uspesno uneta!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Neuspesno unosenje usluge!");
            }
        } catch (IOException ex) {
            Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreiranjeUslugeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKategorijaUsluga;
    private javax.swing.JTextField txtNazivUsluge;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbKategorijaUsluge() {
        try {
            ObjectOutputStream oos = KomunikacijaSaServerom.getInstanca().getOos();
            ObjectInputStream ois = KomunikacijaSaServerom.getInstanca().getOis();
            oos.writeInt(RequestTypes.VRATI_SVE_KATEGORIJE_USLUGA_ZAHTEV);
            oos.flush();

            int tipOdgovora = ois.readInt();
            VratiSveKategorijeUslugaOdgovor odgovor =  (VratiSveKategorijeUslugaOdgovor) ois.readObject();
            cmbKategorijaUsluga.removeAllItems();

            for (KategorijaUsluga kategorija : odgovor.getListaKategorijaUsluga()) {;
                cmbKategorijaUsluga.addItem(kategorija);
            }
        } catch (IOException ex) {
            Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KreiranjeUslugeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
